@extends('layout.layout')

@section('title', 'Program Management | SpiderWEB')

@include('templates.Admin.header')

<section class="w-[80%] h-full flex justify-center items-start bg-gray-50 p-6">

    <div class="w-full max-w-2xl bg-white rounded-lg shadow p-6">

        <!-- Header -->
        <div class="mb-6">
            <h1 class="text-2xl font-bold text-green-700">Add New User</h1>
            <p class="text-sm text-gray-500">Create a new account for a student, teacher or admin</p>
        </div>

        <!-- Form -->
        <form class="flex flex-col gap-5">

            <!-- First & Last Name -->
            <div class="grid grid-cols-2 gap-4">
                <div>
                    <label class="block text-sm font-medium text-gray-700 mb-1">
                        First Name
                    </label>
                    <input 
                        type="text" 
                        name="first_name"
                        placeholder="Enter first name"
                        class="w-full border rounded px-3 py-2 focus:outline-none focus:ring-2 focus:ring-green-400"
                        required
                    >
                </div>

                <div>
                    <label class="block text-sm font-medium text-gray-700 mb-1">
                        Last Name
                    </label>
                    <input 
                        type="text" 
                        name="last_name"
                        placeholder="Enter last name"
                        class="w-full border rounded px-3 py-2 focus:outline-none focus:ring-2 focus:ring-green-400"
                        required
                    >
                </div>
            </div>

            <!-- Email -->
            <div>
                <label class="block text-sm font-medium text-gray-700 mb-1">
                    Email
                </label>
                <input 
                    type="email" 
                    name="email"
                    placeholder="example@mail.com"
                    class="w-full border rounded px-3 py-2 focus:outline-none focus:ring-2 focus:ring-green-400"
                    required
                >
            </div>

            <!-- Password -->
            <div>
                <label class="block text-sm font-medium text-gray-700 mb-1">
                    Password
                </label>
                <input 
                    type="password" 
                    name="password"
                    placeholder="Minimum 8 characters"
                    class="w-full border rounded px-3 py-2 focus:outline-none focus:ring-2 focus:ring-green-400"
                    required
                >
            </div>

            <!-- Role & Class -->
            <div class="grid grid-cols-2 gap-4">

                <!-- Role -->
                <div>
                    <label class="block text-sm font-medium text-gray-700 mb-1">
                        Role
                    </label>
                    <select 
                        name="role"
                        class="w-full border rounded px-3 py-2 focus:outline-none focus:ring-2 focus:ring-green-400"
                        required
                    >
                        <option value="">Select role</option>
                        <option value="student">Student</option>
                        <option value="teacher">Teacher</option>
                        <option value="admin">Admin</option>
                    </select>
                </div>

                <!-- Class -->
                <div>
                    <label class="block text-sm font-medium text-gray-700 mb-1">
                        Class
                    </label>
                    <select 
                        name="class_id"
                        class="w-full border rounded px-3 py-2 focus:outline-none focus:ring-2 focus:ring-green-400"
                    >
                        <option value="">No class (NULL)</option>
                        <option value="1">Class A</option>
                        <option value="2">Class B</option>
                        <!-- Loop classes from DB here -->
                    </select>
                </div>

            </div>

            <!-- Created Date (read-only display, optional) -->
            <div>
                <label class="block text-sm font-medium text-gray-700 mb-1">
                    Created Date
                </label>
                <input 
                    type="text" 
                    value="Auto generated by system"
                    disabled
                    class="w-full bg-gray-100 border rounded px-3 py-2 text-gray-500"
                >
            </div>

            <!-- Actions -->
            <div class="flex justify-end gap-4 pt-4">
                <button 
                    type="button"
                    class="px-4 py-2 rounded border text-gray-700 hover:bg-gray-100"
                >
                    Cancel
                </button>

                <button 
                    type="submit"
                    class="px-5 py-2 rounded bg-green-600 text-white hover:bg-green-700 transition"
                >
                    Create User
                </button>
            </div>

        </form>

    </div>

</section>
